/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetofinalpizzaria;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kauan
 */
public class RealizarPedido extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RealizarPedido.class.getName());
    // Variável para controlar qual pedido está sendo editado. -1 para um novo Pedido
    private int idPedidoEmEdicao = -1;
    
    //Construtor
    public RealizarPedido() {
        initComponents();
        //desabilita inicialmente as partes de itens do pedido
        MenuPedidoCliente.setEnabled(false);
        AreaPedido.setEnabled(false);
        botao1Pedido.setEnabled(false);
        botao2Pedido.setEnabled(false);
        tabelaPedido.setEnabled(false);
        panelPedido.setEnabled(false);
        botaoNovoPedido.setEnabled(false);
        botaoAtualizar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        caixaTextoTelefone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botaoBuscar = new javax.swing.JButton();
        botaoAtualizar = new javax.swing.JButton();
        botaoNovoPedido = new javax.swing.JButton();
        lugarNomeCliente = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelasPedidosCliente = new javax.swing.JTable();
        AreaPedido = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaPedido = new javax.swing.JTable();
        botao2Pedido = new javax.swing.JButton();
        panelPedido = new javax.swing.JPanel();
        labelInformacoes = new javax.swing.JLabel();
        botao1Pedido = new javax.swing.JButton();
        botao1Excluir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuClientes = new javax.swing.JMenu();
        MenuClientesCadastrados = new javax.swing.JMenuItem();
        MenuCadastrarSabor = new javax.swing.JMenu();
        MenuAtualizarPreco = new javax.swing.JMenuItem();
        MenuCadastrarSabor1 = new javax.swing.JMenuItem();
        MenuPedido = new javax.swing.JMenu();
        MenuPedidoCliente = new javax.swing.JMenuItem();
        menuVerPedidos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(245, 245, 220));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encontrar Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Telefone para localizar o cliente");

        botaoBuscar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        botaoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/search.png"))); // NOI18N
        botaoBuscar.setText("Buscar");
        botaoBuscar.addActionListener(this::botaoBuscarActionPerformed);

        botaoAtualizar.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        botaoAtualizar.setText("Atualizar Pedido");
        botaoAtualizar.addActionListener(this::botaoAtualizarActionPerformed);

        botaoNovoPedido.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        botaoNovoPedido.setText("Novo Pedido");
        botaoNovoPedido.addActionListener(this::botaoNovoPedidoActionPerformed);

        lugarNomeCliente.setForeground(new java.awt.Color(0, 0, 0));
        lugarNomeCliente.setText("Cliente:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(caixaTextoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(botaoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lugarNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(botaoAtualizar)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(214, Short.MAX_VALUE)
                    .addComponent(botaoNovoPedido)
                    .addGap(97, 97, 97)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaTextoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lugarNomeCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(106, Short.MAX_VALUE)
                    .addComponent(botaoNovoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(5, 5, 5)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedidos Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setOpaque(false);

        tabelasPedidosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Pedido", "Valor", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tabelasPedidosCliente);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AreaPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Itens do Pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 1, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        AreaPedido.setOpaque(false);

        tabelaPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sabores", "Forma", "Preço", "Área"
            }
        ));
        jScrollPane2.setViewportView(tabelaPedido);

        botao2Pedido.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        botao2Pedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/diskette.png"))); // NOI18N
        botao2Pedido.setText("Salvar Pedido");
        botao2Pedido.addActionListener(this::botao2PedidoActionPerformed);

        panelPedido.setBackground(new java.awt.Color(204, 204, 204));

        labelInformacoes.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        labelInformacoes.setForeground(new java.awt.Color(0, 0, 0));
        labelInformacoes.setText("Resumo Pedido: R$:0.00 | 0 Pizzas");

        javax.swing.GroupLayout panelPedidoLayout = new javax.swing.GroupLayout(panelPedido);
        panelPedido.setLayout(panelPedidoLayout);
        panelPedidoLayout.setHorizontalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInformacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPedidoLayout.setVerticalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPedidoLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(labelInformacoes)
                .addContainerGap())
        );

        botao1Pedido.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        botao1Pedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add.png"))); // NOI18N
        botao1Pedido.setText("Adicionar pizza");
        botao1Pedido.addActionListener(this::botao1PedidoActionPerformed);

        botao1Excluir.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        botao1Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete.png"))); // NOI18N
        botao1Excluir.setText("Excluir");
        botao1Excluir.addActionListener(this::botao1ExcluirActionPerformed);

        javax.swing.GroupLayout AreaPedidoLayout = new javax.swing.GroupLayout(AreaPedido);
        AreaPedido.setLayout(AreaPedidoLayout);
        AreaPedidoLayout.setHorizontalGroup(
            AreaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AreaPedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao2Pedido)
                .addGap(20, 20, 20))
            .addGroup(AreaPedidoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(AreaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AreaPedidoLayout.createSequentialGroup()
                        .addGroup(AreaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelPedido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(AreaPedidoLayout.createSequentialGroup()
                        .addComponent(botao1Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botao1Pedido, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        AreaPedidoLayout.setVerticalGroup(
            AreaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AreaPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AreaPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao1Excluir)
                    .addComponent(botao1Pedido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(panelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botao2Pedido)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addComponent(AreaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(32, 32, 32))
                    .addComponent(AreaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        MenuClientes.setText("Clientes");

        MenuClientesCadastrados.setText("Clientes Cadastrados");
        MenuClientesCadastrados.addActionListener(this::MenuClientesCadastradosActionPerformed);
        MenuClientes.add(MenuClientesCadastrados);

        jMenuBar1.add(MenuClientes);

        MenuCadastrarSabor.setText("Sabor");

        MenuAtualizarPreco.setText("Atualizar Preço");
        MenuAtualizarPreco.addActionListener(this::MenuAtualizarPrecoActionPerformed);
        MenuCadastrarSabor.add(MenuAtualizarPreco);

        MenuCadastrarSabor1.setText("Cadastrar Sabor");
        MenuCadastrarSabor1.addActionListener(this::MenuCadastrarSabor1ActionPerformed);
        MenuCadastrarSabor.add(MenuCadastrarSabor1);

        jMenuBar1.add(MenuCadastrarSabor);

        MenuPedido.setText("Pedido");

        MenuPedidoCliente.setText("Pedido Cliente");
        MenuPedidoCliente.addActionListener(this::MenuPedidoClienteActionPerformed);
        MenuPedido.add(MenuPedidoCliente);

        menuVerPedidos.setText("Visualizar Pedidos");
        menuVerPedidos.addActionListener(this::menuVerPedidosActionPerformed);
        MenuPedido.add(menuVerPedidos);

        jMenuBar1.add(MenuPedido);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //busca no bd o valor por CM²
    private double obterPrecoPorCm2(String nomeSabor) {
        if (nomeSabor == null){
            return 0;
        }
        BancoDados bd = BancoDados.getInstance();
        for (int i = 0; i < bd.getListaSabor().size(); i++) {
            if (bd.getListaSabor().get(i).getSabor().equals(nomeSabor)) {
                return bd.getListaSabor().get(i).getTipo().getPrecoPorCentimentroQuadrado(); 
            }
        }
        return 0;
    }
    // atualiza os itens da tabela do pedido METODO CHAMADO EM NOVA PIZZA
    public void atualizarTabela(Pizza pizza, double valor, double area){ 
        DefaultTableModel modelo = (DefaultTableModel)tabelaPedido.getModel();
        StringBuilder sb = new StringBuilder();
        //salva os sabores na StringBuilder
        for(int i = 0; i< pizza.getSabor().size();i++){
            sb.append(pizza.getSabor().get(i).getSabor()).append(";");
        }
        Object [] linha= {
            sb.toString(),
            pizza.getForma().getClass().getSimpleName(),
            String.format("R$ %.2f", valor),
            String.format("%.2f cm²", area),
        };
        //adiciona pizza na tabela
        modelo.addRow(linha);
        atualizaValorTotal();
    }
    public void atualizaValorTotal(){
        if(tabelaPedido.getRowCount() == 0){
            labelInformacoes.setText("Resumo Pedido: R$:0.00 | 0 Pizzas");  
        }
        else{
            int quantidadePizzas = tabelaPedido.getRowCount();
            double somatorio = 0;
            //soma o valor de todas as pizzas da tabela e mostra na tela
            for(int i = 0; i< quantidadePizzas; i++){
                String valor = (String)tabelaPedido.getValueAt(i, 2);
                valor = valor.replace("R$ ", "").replace(",", ".");
                somatorio += Double.parseDouble(valor); 
            }
            labelInformacoes.setText(String.format("Resumo Pedido: R$ %.2f | %d Pizzas", somatorio, quantidadePizzas));
        }
    }
    //limpa tabela Pedido
    public void limparTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaPedido.getModel();
        modelo.setRowCount(0);
    } 
    //limpa tabela Pedidos do cliente
    public void limparTabela2() {
        DefaultTableModel modelo = (DefaultTableModel) tabelasPedidosCliente.getModel();
        modelo.setRowCount(0);
    } 
    //busca cliente
    private void botaoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoBuscarActionPerformed
        String telefone = caixaTextoTelefone.getText();
        BancoDados bd = BancoDados.getInstance();
        boolean encontrado = false;
        Cliente cliente= null;
        //procura cliente no bd
        for(int i = 0; i<bd.getListaCliente().size();i++){
            if(telefone.equals(bd.getListaCliente().get(i).getTelefone())){
                cliente = bd.getListaCliente().get(i); 
                lugarNomeCliente.setText("Cliente: " + cliente.getNome() + " " + cliente.getSobrenome());
                encontrado = true;
                break;
            }
        }
        //caso nao encontre
        if(encontrado == false){
            JOptionPane.showMessageDialog(this,"Cliente não encontrado!");
            MenuPedidoCliente.setEnabled(false);
            AreaPedido.setEnabled(false);
            botao1Pedido.setEnabled(false);
            botao2Pedido.setEnabled(false);
            tabelaPedido.setEnabled(false);
            panelPedido.setEnabled(false);
            botaoNovoPedido.setEnabled(false);
            botaoAtualizar.setEnabled(false);
            lugarNomeCliente.setText("Cliente: ");
            limparTabela();
            limparTabela2();
            labelInformacoes.setText("Resumo Pedido: R$:0.00 | 0 Pizzas");
            return;
        }
        else{
            //listar todos os pedidos do cliente
            PreecherTabelaPedidoCliente  preenchimento = new PreecherTabelaPedidoCliente();
            tabelasPedidosCliente.setModel(preenchimento.gerarModelo2(cliente));
            //libera esses dois botoes
            botaoAtualizar.setEnabled(true);
            botaoNovoPedido.setEnabled(true);
        }
    }//GEN-LAST:event_botaoBuscarActionPerformed
    //atualizar pedido
    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        int linhaSelecionada = tabelasPedidosCliente.getSelectedRow();
        //caso nenhum pedido selecionado
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um pedido na tabela do cliente para atualizar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String estadoPedido = (String) tabelasPedidosCliente.getValueAt(linhaSelecionada, 2);
        //caso pedido esteja entregue
        if (!estadoPedido.equals("Aberto") && !estadoPedido.equals("A caminho")) {
            JOptionPane.showMessageDialog(this, "Pedidos encerrados nao podem ser alterados.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idPedido = Integer.parseInt(tabelasPedidosCliente.getValueAt(linhaSelecionada, 0).toString());
        // Salva o ID para usar na hora de salvar
        this.idPedidoEmEdicao = idPedido;
        MenuPedidoCliente.setEnabled(true);
        AreaPedido.setEnabled(true);
        botao1Pedido.setEnabled(true);
        botao2Pedido.setEnabled(true);
        tabelaPedido.setEnabled(true);
        panelPedido.setEnabled(true);
        limparTabela();

        BancoDados bd = BancoDados.getInstance();
        Pedido pedidoSelecionado = null;
        //procura o pedido na lista de pedidos do bd
        for (int i = 0; i<bd.getListaPedido().size();i++) {
            Pedido p = bd.getListaPedido().get(i);
            if (p.getIdPedido()== idPedido) { 
                pedidoSelecionado = p;
                break;
            }
        }
        //
        if (pedidoSelecionado != null) {
            //preencher a tabela com os itens do pedido
            for (int j = 0; j<pedidoSelecionado.getPizza().size();j++){ 
                Pizza p = pedidoSelecionado.getPizza().get(j);
                double area = p.getArea();
                double precoPorCm2 = 0;
                //caso pizza tenha 1 sabor
                if(p.getSabor().size()> 1){
                    String nome1 = p.getSabor().get(0).getSabor();
                    String nome2 = p.getSabor().get(1).getSabor();
                    double preco1 = obterPrecoPorCm2(nome1);
                    double preco2 = obterPrecoPorCm2(nome2);
                    precoPorCm2 = (preco1 + preco2)/2;
                }
                //caso pizza tem 2 sabores
                else{
                    String nome1 = p.getSabor().get(0).getSabor();
                    precoPorCm2 = obterPrecoPorCm2(nome1);
                }
                double valorDaPizza = area * precoPorCm2;

                atualizarTabela(p, valorDaPizza, p.getArea());
            }
        }
    }//GEN-LAST:event_botaoAtualizarActionPerformed
    //salvar pedido
    private void botao2PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2PedidoActionPerformed
        //caso tente criar pedido sem nenhuma pizza
        if(tabelaPedido.getRowCount() == 0){
            JOptionPane.showMessageDialog(this,"O pedido nao pode ser criado sem nenhum item", "",JOptionPane.ERROR_MESSAGE);
            return;
        }
        BancoDados bd = BancoDados.getInstance();
        Estado estado = bd.getListaEstado().get(0); 
        String telefone = caixaTextoTelefone.getText();
        boolean encontrado = false;
        Cliente cliente= null;
        //procura cliente no bd
        for(int i = 0; i<bd.getListaCliente().size();i++){
            if(telefone.equals(bd.getListaCliente().get(i).getTelefone())){
                cliente = bd.getListaCliente().get(i); 
                encontrado = true;
                break;
            }
        }
        //caso nao encontre cliente no bd
        if(encontrado == false){
            JOptionPane.showMessageDialog(this,"Erro ao encontrar cliente para atribuir em pedido", "",JOptionPane.ERROR_MESSAGE);
            return;
        }
        int quantidadePizzas = tabelaPedido.getRowCount();
        double valorTotal = 0;
        ArrayList<Pizza> pizzas = new ArrayList<>();
        for(int i = 0; i< quantidadePizzas; i++){
            //lista de sabores da pizza
            ArrayList<Sabor> sabores = new ArrayList<>();
            String valor = (String)tabelaPedido.getValueAt(i, 2);
            valor = valor.replace("R$ ", "").replace(",", ".");
            valorTotal += Double.parseDouble(valor);
            String sabor = (String)tabelaPedido.getValueAt(i, 0);
            // separa os sabores, cada um em uma string
            String[] nomesSabores = sabor.split(";");
            for(int j = 0; j < nomesSabores.length;j++){
                for(int l = 0; l < bd.getListaSabor().size();l++){
                    Sabor s = bd.getListaSabor().get(l);
                    if(s.getSabor().equals(nomesSabores[j])){
                        sabores.add(s);
                        break;
                    }
                }
            }
            String nomeForma = (String)tabelaPedido.getValueAt(i,1);
            Forma f;
            if(nomeForma.equals("Circulo")){
                f = new Circulo();
            }
            else if(nomeForma.equals("Triangulo")){
                f = new Triangulo();
            }
            else if(nomeForma.equals("Quadrado")){
                f = new Quadrado();
            }
            //caso erro no formato da pizza
            else{
                JOptionPane.showMessageDialog(this,"Erro ao encotrar formato pizza", "",JOptionPane.ERROR_MESSAGE);
                return;
            }
            String valorArea = (String)tabelaPedido.getValueAt(i,3);
            valorArea = valorArea.replace(" cm²", "").replace(",", ".");
            double areaConvertida = Double.parseDouble(valorArea); 
            Pizza p = new Pizza(areaConvertida, f ,sabores);
            //adiciona pizza na lista
            pizzas.add(p);
        }
     //Verifica se é uma atualização ou novo
        if (this.idPedidoEmEdicao != -1) {
            //Caso seja atualização, procura o pedido existente e altera os dados
            for (int i = 0; i < bd.getListaPedido().size(); i++) {
                Pedido p = bd.getListaPedido().get(i);
                if (p.getIdPedido() == this.idPedidoEmEdicao) {
                    p.setPizza(pizzas);
                    p.setPrecoTotal(valorTotal); // Atualiza o valor total do pedido
                    break;
                }
            }
            JOptionPane.showMessageDialog(this, "Pedido atualizado com sucesso!");
            
        } else {
            // Caso seja novo pedido, cria um novo ID e adiciona na lista
            int idPedido = bd.getListaPedido().size() + 1;
            Pedido pedido = new Pedido(idPedido, valorTotal, pizzas, estado, cliente);
            
            if(pedido == null){
                JOptionPane.showMessageDialog(this,"Erro ao criar pedido", "",JOptionPane.ERROR_MESSAGE);
                return;
            } else {
                bd.getListaPedido().add(pedido);
                JOptionPane.showMessageDialog(this, "Pedido criado com sucesso!");
            }
        }
        
        //restaura a variável de controle
        this.idPedidoEmEdicao = -1;
        
        MenuPedidoCliente.setEnabled(false);
        AreaPedido.setEnabled(false);
        botao1Pedido.setEnabled(false);
        botao2Pedido.setEnabled(false);
        tabelaPedido.setEnabled(false);
        panelPedido.setEnabled(false);
        botaoNovoPedido.setEnabled(false);
        botaoAtualizar.setEnabled(false);
        lugarNomeCliente.setText("Cliente: ");
        caixaTextoTelefone.setText("");
        
        limparTabela();
        limparTabela2();
        labelInformacoes.setText("Resumo Pedido: R$:0.00 | 0 Pizzas");
    }//GEN-LAST:event_botao2PedidoActionPerformed

    private void botao1PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1PedidoActionPerformed
       NovaPizza np = new NovaPizza(this);
       np.setVisible(true);
    }//GEN-LAST:event_botao1PedidoActionPerformed
    //novo pedido
    private void botaoNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoNovoPedidoActionPerformed
        // Garantir q sera novo pedido
        idPedidoEmEdicao = -1;
        limparTabela();
        MenuPedidoCliente.setEnabled(true);
        AreaPedido.setEnabled(true);
        botao1Pedido.setEnabled(true);
        botao2Pedido.setEnabled(true);
        tabelaPedido.setEnabled(true);
        panelPedido.setEnabled(true);
    }//GEN-LAST:event_botaoNovoPedidoActionPerformed

    private void botao1ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao1ExcluirActionPerformed
        int linhaSelecionada = tabelaPedido.getSelectedRow();
        //caso nenhuma linha selecionada
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this,"Nenhuma linha foi selecionada");
            return;
        }
        DefaultTableModel tabela =(DefaultTableModel) tabelaPedido.getModel();
        //remove linha do modelo da tabela
        tabela.removeRow(linhaSelecionada);
        atualizaValorTotal();
    }//GEN-LAST:event_botao1ExcluirActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void MenuClientesCadastradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuClientesCadastradosActionPerformed
        CadastrarCliente cc = new CadastrarCliente();
        cc.setVisible(true);
    }//GEN-LAST:event_MenuClientesCadastradosActionPerformed

    private void MenuAtualizarPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAtualizarPrecoActionPerformed
        AtualizarPreco atualizar = new AtualizarPreco();
        atualizar.setVisible(true);
    }//GEN-LAST:event_MenuAtualizarPrecoActionPerformed

    private void MenuCadastrarSabor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadastrarSabor1ActionPerformed
        CadastrarSabor cs = new CadastrarSabor();
        cs.setVisible(true);
    }//GEN-LAST:event_MenuCadastrarSabor1ActionPerformed

    private void MenuPedidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPedidoClienteActionPerformed
        RealizarPedido rp = new RealizarPedido();
        rp.setVisible(true);
    }//GEN-LAST:event_MenuPedidoClienteActionPerformed

    private void menuVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuVerPedidosActionPerformed
        VisualizarPedidos vp = new VisualizarPedidos();
        vp.setVisible(true);
    }//GEN-LAST:event_menuVerPedidosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RealizarPedido().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AreaPedido;
    private javax.swing.JMenuItem MenuAtualizarPreco;
    private javax.swing.JMenu MenuCadastrarSabor;
    private javax.swing.JMenuItem MenuCadastrarSabor1;
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenuItem MenuClientesCadastrados;
    private javax.swing.JMenu MenuPedido;
    private javax.swing.JMenuItem MenuPedidoCliente;
    private javax.swing.JButton botao1Excluir;
    private javax.swing.JButton botao1Pedido;
    private javax.swing.JButton botao2Pedido;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoBuscar;
    private javax.swing.JButton botaoNovoPedido;
    private javax.swing.JTextField caixaTextoTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelInformacoes;
    private javax.swing.JLabel lugarNomeCliente;
    private javax.swing.JMenuItem menuVerPedidos;
    private javax.swing.JPanel panelPedido;
    private javax.swing.JTable tabelaPedido;
    private javax.swing.JTable tabelasPedidosCliente;
    // End of variables declaration//GEN-END:variables
}
